# Generated by Django 5.2.7 on 2025-10-23 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='mobile_reference',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Referencia de Pago Móvil'),
        ),
        migrations.AddField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Efectivo'), ('card', 'Punto de Venta'), ('mobile', 'Pago Móvil')], default='cash', max_length=20, verbose_name='Método de Pago'),
        ),
    ]
