# Generated by Django 5.2.5 on 2025-12-04 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0002_sale_mobile_reference_sale_payment_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("card", "Punto de Venta"),
                    ("cash", "Efectivo"),
                    ("mobile", "Pago Móvil"),
                ],
                default="cash",
                max_length=20,
                verbose_name="Método de Pago",
            ),
        ),
    ]
