# Generated by Django 5.2.4 on 2025-07-31 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.TextField(blank=True, verbose_name='Dirección')),
                ('credit_limit_bs', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Límite de Crédito (Bs)')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CreditPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_bs', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto (Bs)')),
                ('payment_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Pago')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_payments', to=settings.AUTH_USER_MODEL, verbose_name='Recibido por')),
            ],
            options={
                'verbose_name': 'Pago de Crédito',
                'verbose_name_plural': 'Pagos de Créditos',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='CustomerCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_bs', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto (Bs)')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('date_due', models.DateField(verbose_name='Fecha de Vencimiento')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Pagado')),
                ('date_paid', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Pago')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credits', to='customers.customer', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Crédito de Cliente',
                'verbose_name_plural': 'Créditos de Clientes',
                'ordering': ['-date_created'],
            },
        ),
    ]
