# Generated by Django 5.2.4 on 2025-07-31 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customercredit',
            name='sale',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='credit', to='sales.sale', verbose_name='Venta'),
        ),
        migrations.AddField(
            model_name='creditpayment',
            name='credit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='customers.customercredit', verbose_name='Crédito'),
        ),
    ]
