# Generated by Django - customers/migrations/0004_add_payment_method_to_credit_payment.py

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_add_usd_fields_to_credits'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditpayment',
            name='payment_method',
            field=models.CharField(
                choices=[
                    ('cash', 'Efectivo'),
                    ('card', 'Punto de Venta'),
                    ('mobile', 'Pago Móvil')
                ],
                default='cash',
                max_length=20,
                verbose_name='Método de Pago'
            ),
        ),
        migrations.AddField(
            model_name='creditpayment',
            name='mobile_reference',
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name='Referencia de Pago Móvil'
            ),
        ),
    ]
