# Generated by Django 5.2.6 on 2026-03-05 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_add_payment_method_to_credit_payment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerGeneralPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_bs', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto (Bs)')),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto (USD)')),
                ('exchange_rate_used', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Tasa Utilizada')),
                ('payment_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('payment_method', models.CharField(choices=[('card', 'Punto de Venta'), ('cash', 'Efectivo'), ('mobile', 'Pago Móvil')], default='cash', max_length=20, verbose_name='Método de Pago')),
                ('mobile_reference', models.CharField(blank=True, max_length=50, null=True, verbose_name='Referencia Pago Móvil')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='general_payments', to='customers.customer', verbose_name='Cliente')),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='general_payments_received', to=settings.AUTH_USER_MODEL, verbose_name='Recibido por')),
            ],
            options={
                'verbose_name': 'Pago General de Cliente',
                'verbose_name_plural': 'Pagos Generales de Clientes',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.AddField(
            model_name='creditpayment',
            name='general_payment',
            field=models.ForeignKey(blank=True, help_text='Generado automáticamente por un pago general', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_payments', to='customers.customergeneralpayment', verbose_name='Pago General Origen'),
        ),
    ]
