# Generated by Django 5.2.6 on 2025-09-03 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyClose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Fecha')),
                ('sales_count', models.IntegerField(verbose_name='Cantidad de Ventas')),
                ('sales_total_bs', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total Ventas (Bs)')),
                ('expenses_total_bs', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total Gastos (Bs)')),
                ('profit_bs', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Ganancia (Bs)')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('closed_at', models.DateTimeField(auto_now_add=True, verbose_name='Cerrado el')),
                ('closed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_closes', to=settings.AUTH_USER_MODEL, verbose_name='Cerrado por')),
            ],
            options={
                'verbose_name': 'Cierre Diario',
                'verbose_name_plural': 'Cierres Diarios',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('rent', 'Alquiler'), ('utilities', 'Servicios'), ('salaries', 'Salarios'), ('maintenance', 'Mantenimiento'), ('taxes', 'Impuestos'), ('other', 'Otros')], max_length=20, verbose_name='Categoría')),
                ('description', models.CharField(max_length=255, verbose_name='Descripción')),
                ('amount_bs', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto (Bs)')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('receipt_number', models.CharField(blank=True, max_length=50, verbose_name='Número de Recibo')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Gasto',
                'verbose_name_plural': 'Gastos',
                'ordering': ['-date'],
            },
        ),
    ]
