# Generated by Django 5.2.6 on 2025-09-10 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('salaries', 'Sueldos de Empleados'), ('repairs', 'Reparaciones'), ('improvements', 'Mejoras en la Bodega'), ('supplies', 'Materiales de Trabajo'), ('rent', 'Alquiler'), ('utilities', 'Servicios (Luz, Agua, Internet)'), ('maintenance', 'Mantenimiento'), ('taxes', 'Impuestos'), ('other', 'Otros')], max_length=20, verbose_name='Categoría'),
        ),
        migrations.CreateModel(
            name='ExpenseReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='expense_receipts/%Y/%m/', verbose_name='Archivo')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Descripción')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Subido el')),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='finances.expense', verbose_name='Gasto')),
            ],
            options={
                'verbose_name': 'Comprobante de Gasto',
                'verbose_name_plural': 'Comprobantes de Gastos',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
