# Generated by Django 5.2.6 on 2025-09-03 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('contact_person', models.CharField(blank=True, max_length=100, verbose_name='Persona de Contacto')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.TextField(blank=True, verbose_name='Dirección')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SupplierOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Orden')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('received', 'Recibido'), ('cancelled', 'Cancelado')], default='pending', max_length=20, verbose_name='Estado')),
                ('received_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Recepción')),
                ('total_bs', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total (Bs)')),
                ('paid', models.BooleanField(default=False, verbose_name='Pagado')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_orders', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='suppliers.supplier', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Orden de Proveedor',
                'verbose_name_plural': 'Órdenes de Proveedores',
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='SupplierOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Cantidad')),
                ('price_bs', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio (Bs)')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='suppliers.supplierorder', verbose_name='Orden')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_order_items', to='inventory.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Ítem de Orden',
                'verbose_name_plural': 'Ítems de Órdenes',
            },
        ),
    ]
