# Generated by Django 5.2.6 on 2025-09-10 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierorder',
            name='exchange_rate_used',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Tasa Bs/USD utilizada en esta orden', max_digits=12, verbose_name='Tasa de Cambio Utilizada'),
        ),
        migrations.AddField(
            model_name='supplierorder',
            name='total_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total (USD)'),
        ),
        migrations.AddField(
            model_name='supplierorderitem',
            name='price_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Precio (USD)'),
        ),
        migrations.AlterField(
            model_name='supplierorderitem',
            name='price_bs',
            field=models.DecimalField(decimal_places=2, help_text='Se calcula automáticamente basado en USD y tasa de cambio', max_digits=12, verbose_name='Precio (Bs)'),
        ),
    ]
