# Generated by Django 5.2.6 on 2025-09-11 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_supplierorder_exchange_rate_used_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierorder',
            name='total_bs',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total (Bs)'),
        ),
    ]
