# Generated by Django 5.2.6 on 2025-09-13 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0003_alter_supplierorder_total_bs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierorderitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad'),
        ),
    ]
