# Generated by Django 5.2.6 on 2025-09-14 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0004_alter_supplierorderitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierorderitem',
            name='price_bs',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Se calcula automáticamente basado en USD y tasa de cambio', max_digits=12, verbose_name='Precio (Bs)'),
        ),
    ]
