# Generated by Django 5.2.6 on 2026-02-25 17:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0006_supplier_payment_system'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='supplierorder',
            index=models.Index(fields=['supplier', 'status'], name='order_supplier_status_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierorder',
            index=models.Index(fields=['status', '-order_date'], name='order_status_date_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierorder',
            index=models.Index(fields=['paid', '-order_date'], name='order_paid_date_idx'),
        ),
    ]
