# Generated by Django 5.2.6 on 2026-03-07 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0007_supplierorder_order_supplier_status_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierorderitem',
            name='selling_price_usd',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio de venta sugerido al recibir la orden', max_digits=12, null=True, verbose_name='Precio de Venta (USD)'),
        ),
    ]
