# Generated by Django 5.2.4 on 2025-07-31 14:28

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalProduct',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('barcode', models.CharField(db_index=True, max_length=50, verbose_name='Código de Barras')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('image', models.TextField(blank=True, max_length=100, null=True, verbose_name='Imagen')),
                ('purchase_price_bs', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio de Compra (Bs)')),
                ('selling_price_bs', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio de Venta (Bs)')),
                ('stock', models.IntegerField(default=0, verbose_name='Stock Actual')),
                ('min_stock', models.IntegerField(default=5, verbose_name='Stock Mínimo')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Actualizado el')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('category', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.category', verbose_name='Categoría')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Producto',
                'verbose_name_plural': 'historical Productos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('barcode', models.CharField(max_length=50, unique=True, verbose_name='Código de Barras')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Imagen')),
                ('purchase_price_bs', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio de Compra (Bs)')),
                ('selling_price_bs', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio de Venta (Bs)')),
                ('stock', models.IntegerField(default=0, verbose_name='Stock Actual')),
                ('min_stock', models.IntegerField(default=5, verbose_name='Stock Mínimo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='inventory.category', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_type', models.CharField(choices=[('add', 'Agregar'), ('remove', 'Eliminar'), ('set', 'Establecer')], max_length=10, verbose_name='Tipo de Ajuste')),
                ('quantity', models.IntegerField(verbose_name='Cantidad')),
                ('previous_stock', models.IntegerField(verbose_name='Stock Previo')),
                ('new_stock', models.IntegerField(verbose_name='Nuevo Stock')),
                ('reason', models.TextField(verbose_name='Razón')),
                ('adjusted_at', models.DateTimeField(auto_now_add=True, verbose_name='Ajustado el')),
                ('adjusted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_adjustments', to=settings.AUTH_USER_MODEL, verbose_name='Ajustado por')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='inventory.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Ajuste de Inventario',
                'verbose_name_plural': 'Ajustes de Inventario',
                'ordering': ['-adjusted_at'],
            },
        ),
    ]
