# Generated by Django 5.2.4 on 2025-08-06 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCombo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Combo')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('combo_price_bs', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio del Combo (Bs)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
            ],
            options={
                'verbose_name': 'Combo de Productos',
                'verbose_name_plural': 'Combos de Productos',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='bulk_min_quantity',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Cantidad Mínima al Mayor'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='bulk_price_bs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Precio al Mayor (Bs)'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='is_bulk_pricing',
            field=models.BooleanField(default=False, verbose_name='Precio al Mayor'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='unit_type',
            field=models.CharField(choices=[('unit', 'Unidad'), ('kg', 'Kilogramo'), ('gram', 'Gramo'), ('liter', 'Litro'), ('ml', 'Mililitro')], default='unit', max_length=10, verbose_name='Tipo de Unidad'),
        ),
        migrations.AddField(
            model_name='product',
            name='bulk_min_quantity',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Cantidad Mínima al Mayor'),
        ),
        migrations.AddField(
            model_name='product',
            name='bulk_price_bs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Precio al Mayor (Bs)'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_bulk_pricing',
            field=models.BooleanField(default=False, verbose_name='Precio al Mayor'),
        ),
        migrations.AddField(
            model_name='product',
            name='unit_type',
            field=models.CharField(choices=[('unit', 'Unidad'), ('kg', 'Kilogramo'), ('gram', 'Gramo'), ('liter', 'Litro'), ('ml', 'Mililitro')], default='unit', max_length=10, verbose_name='Tipo de Unidad'),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='min_stock',
            field=models.DecimalField(decimal_places=3, default=5, max_digits=10, verbose_name='Stock Mínimo'),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='stock',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Stock Actual'),
        ),
        migrations.AlterField(
            model_name='product',
            name='min_stock',
            field=models.DecimalField(decimal_places=3, default=5, max_digits=10, verbose_name='Stock Mínimo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Stock Actual'),
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Cantidad')),
                ('combo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='inventory.productcombo', verbose_name='Combo')),
            ],
        ),
        migrations.CreateModel(
            name='ComboItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Cantidad')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product', verbose_name='Producto')),
                ('combo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.productcombo', verbose_name='Combo')),
            ],
            options={
                'verbose_name': 'Ítem de Combo',
                'verbose_name_plural': 'Ítems de Combo',
                'unique_together': {('combo', 'product')},
            },
        ),
    ]
