# Generated by Django 5.2.6 on 2025-09-10 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='purchase_price_bs',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Se actualiza automáticamente con la tasa de cambio', max_digits=12, verbose_name='Precio de Compra (Bs)'),
        ),
        migrations.AddField(
            model_name='product',
            name='purchase_price_bs',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Se actualiza automáticamente con la tasa de cambio', max_digits=12, verbose_name='Precio de Compra (Bs)'),
        ),
    ]
