# Generated by Django 5.2.4 on 2025-08-08 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_productcombo_historicalproduct_bulk_min_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryadjustment',
            name='new_stock',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Nuevo Stock'),
        ),
        migrations.AlterField(
            model_name='inventoryadjustment',
            name='previous_stock',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Stock Previo'),
        ),
        migrations.AlterField(
            model_name='inventoryadjustment',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Cantidad'),
        ),
    ]
