# Generated by Django 5.2.6 on 2025-09-11 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_historicalproduct_purchase_price_bs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='selling_price_bs',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Se actualiza automáticamente con la tasa de cambio', max_digits=12, verbose_name='Precio de Venta (Bs)'),
        ),
        migrations.AddField(
            model_name='product',
            name='selling_price_bs',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Se actualiza automáticamente con la tasa de cambio', max_digits=12, verbose_name='Precio de Venta (Bs)'),
        ),
    ]
