# Generated by Django 5.2.5 on 2025-12-04 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_historicalproduct_selling_price_bs_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalproduct",
            name="purchase_price_bs",
            field=models.DecimalField(
                decimal_places=5,
                default=0,
                help_text="Se actualiza automáticamente con la tasa de cambio",
                max_digits=12,
                verbose_name="Precio de Compra (Bs)",
            ),
        ),
        migrations.AlterField(
            model_name="historicalproduct",
            name="purchase_price_usd",
            field=models.DecimalField(
                decimal_places=5, max_digits=10, verbose_name="Precio de Compra (USD)"
            ),
        ),
        migrations.AlterField(
            model_name="historicalproduct",
            name="selling_price_bs",
            field=models.DecimalField(
                decimal_places=5,
                default=0,
                help_text="Se actualiza automáticamente con la tasa de cambio",
                max_digits=12,
                verbose_name="Precio de Venta (Bs)",
            ),
        ),
        migrations.AlterField(
            model_name="historicalproduct",
            name="selling_price_usd",
            field=models.DecimalField(
                decimal_places=5, max_digits=10, verbose_name="Precio de Venta (USD)"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="purchase_price_bs",
            field=models.DecimalField(
                decimal_places=5,
                default=0,
                help_text="Se actualiza automáticamente con la tasa de cambio",
                max_digits=12,
                verbose_name="Precio de Compra (Bs)",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="purchase_price_usd",
            field=models.DecimalField(
                decimal_places=5, max_digits=10, verbose_name="Precio de Compra (USD)"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="selling_price_bs",
            field=models.DecimalField(
                decimal_places=5,
                default=0,
                help_text="Se actualiza automáticamente con la tasa de cambio",
                max_digits=12,
                verbose_name="Precio de Venta (Bs)",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="selling_price_usd",
            field=models.DecimalField(
                decimal_places=5, max_digits=10, verbose_name="Precio de Venta (USD)"
            ),
        ),
    ]
