# Generated by Django 5.2.4 on 2025-08-08 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_inventoryadjustment_new_stock_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SaleItem',
        ),
    ]
