# Generated by Django 5.2.4 on 2025-08-08 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_delete_saleitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comboitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad'),
        ),
    ]
