# Generated by Django 5.2.4 on 2025-08-08 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_comboitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproduct',
            name='bulk_min_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cantidad Mínima al Mayor'),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='min_stock',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=10, verbose_name='Stock Mínimo'),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Stock Actual'),
        ),
        migrations.AlterField(
            model_name='inventoryadjustment',
            name='previous_stock',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Stock Previo'),
        ),
        migrations.AlterField(
            model_name='inventoryadjustment',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='product',
            name='bulk_min_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cantidad Mínima al Mayor'),
        ),
        migrations.AlterField(
            model_name='product',
            name='min_stock',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=10, verbose_name='Stock Mínimo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Stock Actual'),
        ),
    ]
